# Deployment-blue.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-exchange-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-exchange-blue
  template:
    metadata:
      labels:
        app: crypto-exchange-blue
    spec:
      containers:
        - name: crypto-exchange-container
          image: crypto-exchange-service:blue-version
          ports:
            - containerPort: 3000
