apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-exchange-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-exchange-service
  template:
    metadata:
      labels:
        app: crypto-exchange-service
    spec:
      containers:
        - name: crypto-exchange-container
          image: crypto-exchange-service:latest
          ports:
            - containerPort: 3000
