apiVersion: v1
kind: Service
metadata:
  name: crypto-exchange-service
spec:
  selector:
    app: crypto-exchange-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
